### ISSUE TITLE
Not clear on how to change theme on Linux

### ISSUE THREAD

**Issue by hopelessdecoy** [PintaProject/pintaproject.github.io#7]
I see dark theme mentioned here an there, including in the bug fix log. However there is no clear way to change the theme. My OS (Kubuntu 23) is in dark mode, GTK is set to a dark mode but Pinta remains blindingly in light theme. Am I missing a settings option or a config file? Using the Snap currently but also tried the flatpak with no luck, the regular package in Discover seems outdated so haven't tried that. Any help would be appreciated, really love the tool.

**Comment by hopelessdecoy** [comment]
For anyone who finds this preprend:
`env GTK_THEME=Adwaita:dark`

to the .desktop file and it will launch Pinta in dark mode, this works for the Snap version at least

**Comment by cameronwhite** [comment]
Thanks for noting the solution! Offhand I'm not sure if this was caused by something on the snap side with being unaware of the system theme, or because it's GTK3 and not GTK4

With the future Pinta 2.2 release we'll be using `libadwaita` and defaulting to a dark theme

**Comment by hopelessdecoy** [comment]
> Thanks for noting the solution! Offhand I'm not sure if this was caused by something on the snap side with being unaware of the system theme, or because it's GTK3 and not GTK4
> 
> With the future Pinta 2.2 release we'll be using `libadwaita` and defaulting to a dark theme

Good idea! Dark theme is pretty popular these days, in the future I think having themeing in an app preferences menu is the best way. Then you don't have to worry about technologies, and can control the quality of the GUI. Thank you for working on Pinta!
